[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  publish = "dist/spa"
  command = "quasar build"

[context.production.environment]
  APP_NAME = "Telos Block Explorer"
  NODE_VERSION = "14"
  # SHOW_SIDEBAR = "true"
  CHAIN_NAME = "telos"

[context.develop.environment]
  APP_NAME = "Telos Testnet Block Explorer"
  NODE_VERSION = "14"
  CHAIN_NAME = "telos-testnet"
  # SHOW_SIDEBAR = "true"

